### ISSUE TITLE
Add static file support

### ISSUE THREAD

**Issue by NHibiki** [NHibiki/pm5#19]
In ml5 / p5, static files are significant. Users might want to load pictures, sounds or textures. So static files support should also be considered in this situation.

One solution is to use `copy-webpack-plugin` webpack plugin to copy files from `static` to `dist` in order to serve static files.

Anyone has better ideas?

**Comment by WenheLI** [comment]
@NHibiki Parcel can do static serving with one command line.
See [here](https://parceljs.org/cli.html) 
Webpack can be quite heavy in some cases.

**Comment by DaKoala** [comment]
If webpack is used, copy plugin is a quick solution

**Comment by NHibiki** [comment]
@WenheLI, Would you like to re-configure the existing solution [here](https://github.com/DaKoala/p5-TypeScript-boilerplate) to parcel? I am glad to check it out.

**Comment by WenheLI** [comment]
Closed #24
